apiVersion: v2
name: dpp-platform
description: Digital Product Passport Platform â€” AAS/IDTA DPP4.0 compliant
version: 0.1.0
appVersion: "0.1.0"
type: application
maintainers:
  - name: DPP Platform Team
keywords:
  - digital-product-passport
  - aas
  - catena-x
  - edc
