{{- if .Values.frontend.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dpp-platform.componentFullname" (dict "context" . "component" "frontend") }}
  namespace: {{ include "dpp-platform.namespace" . }}
  labels:
    {{- include "dpp-platform.componentLabels" (dict "context" . "component" "frontend") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dpp-platform.componentFullname" (dict "context" . "component" "frontend") }}
  minReplicas: {{ .Values.frontend.hpa.minReplicas }}
  maxReplicas: {{ .Values.frontend.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.hpa.targetCPU }}
{{- end }}
