apiVersion: v1
kind: Service
metadata:
  name: {{ include "dpp-platform.componentFullname" (dict "context" . "component" "frontend") }}
  namespace: {{ include "dpp-platform.namespace" . }}
  labels:
    {{- include "dpp-platform.componentLabels" (dict "context" . "component" "frontend") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dpp-platform.selectorLabels" (dict "context" . "component" "frontend") | nindent 4 }}
